### ISSUE TITLE
Why isn't bitcode enabled?

### ISSUE THREAD

**Issue by yusuftor** [red5pro/streaming-ios#114]
All modern frameworks use bitcode, but I've had to turn bitcode off within my app in order to use red5pro! Please update.

**Comment by beetlejesss** [comment]
We don’t release our lib as bitcode because it would make it much easier to decompile and expose proprietary information in our code.

If you need a version with bitcode enabled, we should discuss on a call to understand your requirements and how to best accommodate your situation. Please send an email to info@red5pro.com and someone will get in touch with you about scheduling the call.

**Comment by yusuftor** [comment]
Sorry, I've moved to using OpenTok now. That's due to the bitcode issue, and having to add @objc above my View controllers that caused problems with the Storyboard. Also I strongly advise you to enable using Cocoapods for installation. I managed to get OpenTok working within an hour, whereas I struggled for days trying to set up Red5Pro.
