### ISSUE TITLE
missing required architecture x86_64 

### ISSUE THREAD

**Issue by OmarTawashi** [red5pro/streaming-ios#18]
hello 
i am interested with red5 service , but the iOS library R5Streaming.framework has some issues missing required architecture x86_64

can you rebuild R5Streaming.framework to avoid this error in Xcode 7.2

**Comment by mrchrisallen** [comment]
Hi Omar, 

Thanks for trying out Red5 Pro! 

You are getting that message because we don't have support for hardware encoding in the emulator. Thus the missing x86 architecture. It does work directly on the iOS device though. We will look into adding support for the emulator in a future version. 

Will that work for you? Or is there a reason you absolutely must test in the emulator?
