### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by KiranMantana** [red5pro/streaming-ios#60]
Team, 

Trying Red5Pro for Live chat in our application, So following the steps given in the Website, I added the "R5Streaming.framework" in my project and run the App in iPhone 5S with iOS 10+, the Deployment target we are using is 8.0

I am getting the below issue 

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in R5Streaming(R5VideoViewController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you pls tell what i am missing.

**Comment by HoldenMills** [comment]
Hello,

My apologies for the delay in getting back to you.  Please take a look at [this FAQ](https://red5pro.zendesk.com/hc/en-us/articles/220507567).  Included in that link are example applications that should help you get everything started.  

If you are still running into problems, please submit a support ticket so that we can keep track of your issue.  Please make sure to give us as much information as possible so that we can get you a complete and efficient answer.

Best,
Holden
